#ifndef MINDVISION_QOBJECT_GLOBAL_H
#define MINDVISION_QOBJECT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MINDVISION_QOBJECT_LIBRARY)
#  define MINDVISION_QOBJECT_EXPORT Q_DECL_EXPORT
#else
#  define MINDVISION_QOBJECT_EXPORT Q_DECL_IMPORT
#endif

#endif // MINDVISION_QOBJECT_GLOBAL_H
